import type { Metadata } from "next";

import "./../globals.css";
import Header from "@/components/Header";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "ویرالرن",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl">
      <head>
        <meta
          name="author"
          content="آروین ویرا"
        />
        <meta
          name="designer"
          content="آروین ویرا"
        />
        <meta
          name="developer"
          content="آروین ویرا"
        />
        <meta
          name="generator"
          content="آروین ویرا"
        />
      </head>
      <body className={"antialiased"}>
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
